name: Deploy Kubernetes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Apply manifests no cluster
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar kubectl
        uses: azure/setup-kubectl@v4

      - name: Configurar kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Aplicar manifests da aplicação
        run: |
          kubectl apply -f k8s/redis-pod.yaml
          kubectl apply -f k8s/redis-clusterip.yaml
          kubectl apply -f k8s/deployment.yaml

      - name: Aplicar manifests de monitoramento
        run: kubectl apply -f k8s/monitoring/

      - name: Aguardar rollout da aplicação
        run: kubectl rollout status deployment/themovie-app --timeout=180s

      - name: Aguardar rollout do Prometheus
        run: kubectl rollout status deployment/prometheus --timeout=180s

      - name: Aguardar rollout do Grafana
        run: kubectl rollout status deployment/grafana --timeout=180s

      - name: Verificar status final
        run: |
          kubectl get pods
          kubectl get svc